/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and the orgs they belong to. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the signed-in user's profile (name, locale, timezone). */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The social identities linked to the signed-in user. */
        get: operations["listMyIdentities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/identities/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unlink a social identity from the signed-in user.
         * @description On success returns 204 with no body.
         */
        delete: operations["unlinkMyIdentity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The orgs the signed-in user belongs to. */
        get: operations["listOrgs"];
        put?: never;
        /** Create a new org with the caller as owner. */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** One org the caller is a member of. */
        get: operations["getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke all of the user's sessions.
         * @description On success returns 204 with no body.
         */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** The members of the org with their role and user info. */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave the org. The last owner must transfer ownership first.
         * @description On success returns 204 with no body.
         */
        delete: operations["leaveOrg"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member from the org.
         * @description On success returns 204 with no body.
         */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Change a member's role. */
        patch: operations["changeMemberRole"];
        trace?: never;
    };
    "/orgs/{orgId}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand ownership to another member (owner only). The new owner must already be a member. The acting owner may step down to admin or stay an owner.
         * @description On success returns 204 with no body.
         */
        post: operations["transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** The pending invitations for the org. */
        get: operations["listInvitations"];
        put?: never;
        /** Invite a teammate by email with a target role. */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a pending invitation, freeing its reserved seat.
         * @description On success returns 204 with no body.
         */
        delete: operations["revokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/invitations/{id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend a pending invitation with a fresh token and 7-day expiry. */
        post: operations["resendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        /** Preview an invitation by its token (org name, role, inviter). Usable pre-login via the token capability, so the accept page can render before sign-in. */
        get: operations["getInvitationPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation. Requires a signed-in session whose verified email matches the invited email; creates the membership and occupies the seat. */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** The org's API keys (metadata only; the secret is never returned). */
        get: operations["listAPIKeys"];
        put?: never;
        /** Create an API key. The full secret (pulse_sk_...) is returned exactly once in this response and never again. Role is member or admin only. */
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key. The key fails auth immediately after.
         * @description On success returns 204 with no body.
         */
        delete: operations["revokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** The org's outbound webhooks (the signing secret is never returned). */
        get: operations["listWebhooks"];
        put?: never;
        /** Register an outbound webhook. The signing secret is returned exactly once in this response and never again. url must be https. */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** One outbound webhook (the signing secret is redacted). */
        get: operations["getWebhook"];
        /** Update an outbound webhook's url, enabled flag, and subscribed events. */
        put: operations["updateWebhook"];
        post?: never;
        /**
         * Delete an outbound webhook. Pulse Pager stops delivering to it immediately.
         * @description On success returns 204 with no body.
         */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/webhooks/{id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the signing secret. The new secret is returned exactly once in this response; the old one stops verifying immediately. */
        post: operations["rotateWebhookSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * The active org's plan, usage, and caps (owner/admin).
         * @description The org's current plan with usage vs caps (monitors, seats, status pages) and the plan floors/flags. Billing and usage are viewable by owner and admin only (PRD-006 9); member and viewer get a 403 and feel limits through the per-field upsell errors on writes instead.
         */
        get: operations["getEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The public plan catalog (tiers and their limits).
         * @description The plan tiers and their limits (PRD-006 3) so the FE can render a plan comparison / upgrade table without hardcoding. Reference config, not per-org data; usage vs caps for the active org is GET /orgs/{orgId}/entitlements.
         */
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listMonitors"];
        put?: never;
        post: operations["createMonitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/monitors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getMonitor"];
        put: operations["updateMonitor"];
        post?: never;
        /** @description On success returns 204 with no body. */
        delete: operations["deleteMonitor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/monitors/{id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a check now. It enqueues one probe per region (like a scheduled check) and returns 202 immediately; the per-region progress shows up in the monitor's live region states (poll getMonitorRegionStates). 409 if a check is already running, the monitor is disabled, or you are within the per-monitor cooldown; 429 if you are over the sustained manual-check budget. */
        post: operations["checkNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/monitor-region-states": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** The live per-region check state for the org's monitors (RFC-004 §9): each monitor maps to its regions' current state (scheduled/running/done/failed) with the last outcome. The frontend polls this to render a chip per region. Pass monitor_id to fetch one monitor. Monitors with no live state are omitted. */
        get: operations["getMonitorRegionStates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/monitors/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["listResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/monitors/{id}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["listMonitorIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/monitors/{id}/last-failure": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** The captured response from the monitor's most recent failed check (PRD-002 3.8). */
        get: operations["getLastFailure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/channel-types": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** The channel-type catalog: every notification channel type, its config-field schema, and whether the org's plan includes it. Drives the channel picker and config forms with no hardcoding (RFC-007a, PRD-006 section 3). */
        get: operations["getChannelTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listChannels"];
        put?: never;
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateChannel"];
        post?: never;
        /** @description On success returns 204 with no body. */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/channels/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sends a one-off test message to the channel. On success returns 204 with no body; the outcome is the status alone (204 delivered, 422 provider error). */
        post: operations["testChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** The org's incidents across all monitors, newest first (PRD-002 4). status filters to currently open incidents; the default returns all. */
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** One incident with its annotation timeline (PRD-002 4). Any member may view. */
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/incidents/{id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a note to the incident timeline (PRD-002 4). Member+ may annotate. */
        post: operations["addIncidentAnnotation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/incidents/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually close an open incident as an operator override (PRD-002 4). Owner or admin only. Sets a distinct manual close_reason and emits no recovery notification. An already-closed incident is a 409. */
        post: operations["closeIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/status-pages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listStatusPages"];
        put?: never;
        /** Create a status page (member+; PRD-004 10). */
        post: operations["createStatusPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/status-pages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getStatusPage"];
        /** Update a status page and its displayed monitors (member+). */
        put: operations["updateStatusPage"];
        post?: never;
        /** @description On success returns 204 with no body. */
        delete: operations["deleteStatusPage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/status-pages/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Publish or unpublish a status page (member+; PRD-004 6). Publishing makes the public URL resolve; unpublishing returns it to draft and stops resolving. */
        put: operations["publishStatusPage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/status-pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** The public, unauthenticated data endpoint a published status page renders from (PRD-004 3.6, 8). No auth, no org context. Returns only the public-safe projection; a draft or unknown slug is a 404 (PRD-004 6). Read-mostly and cacheable so the page stays up during the customer's own incident (PRD-004 8). */
        get: operations["getPublicStatusPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Status: "up" | "down" | "disabled" | "pending";
        /** @enum {string} */
        CoverageStatus: "up" | "down" | "disabled" | "pending" | "coverage-degraded";
        /** @enum {string} */
        Method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD";
        /** @enum {string} */
        ChannelType: "slack" | "discord" | "webhook" | "smtp" | "pagerduty" | "opsgenie" | "telegram" | "teams" | "twilio";
        /** @enum {string} */
        FailureReason: "connection_error" | "timeout" | "status_mismatch" | "latency_exceeded" | "body_assertion_failed" | "blocked_target";
        /** @enum {string} */
        CloseReason: "recovered" | "disabled" | "manual";
        /** @enum {string} */
        Role: "owner" | "admin" | "member" | "viewer";
        /** @enum {string} */
        IdentityProviderName: "google" | "github";
        /** @enum {string} */
        Plan: "free" | "starter" | "team" | "business";
        /** @enum {string} */
        DownPolicy: "any" | "quorum" | "all";
        /** @enum {string} */
        ResultsRange: "24h" | "7d" | "90d";
        Error: {
            code: string;
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
        OrgMembership: {
            org_id: string;
            name: string;
            slug: string;
            role: components["schemas"]["Role"];
            plan: components["schemas"]["Plan"];
        };
        Me: {
            user_id: string;
            email: string;
            name: string;
            avatar_url: string | null;
            locale: string;
            timezone: string;
            orgs: components["schemas"]["OrgMembership"][];
        };
        /** @description Editable profile fields. All optional; an omitted field is left unchanged. */
        MeUpdate: {
            name?: string;
            locale?: string;
            timezone?: string;
        };
        Identity: {
            provider: components["schemas"]["IdentityProviderName"];
            provider_user_id: string;
            /** Format: date-time */
            created_at: string;
        };
        OrgInput: {
            name: string;
            slug?: string;
        };
        Member: {
            user_id: string;
            email: string;
            name: string;
            avatar_url: string | null;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            joined_at: string;
        };
        MemberRoleUpdate: {
            role: components["schemas"]["Role"];
        };
        /** @description Hand ownership to another member. step_down makes the acting owner an admin; false keeps them a co-owner (PRD-001 4.7). */
        TransferOwnership: {
            user_id: string;
            step_down?: boolean;
        };
        Invitation: {
            id: string;
            email: string;
            role: components["schemas"]["Role"];
            state: components["schemas"]["InvitationState"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            invited_by?: string | null;
        };
        InvitationInput: {
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            locale?: string;
        };
        /** @description API key metadata. The secret is shown once at creation and never stored in clear, so it is never present here; prefix is the non-secret leading chars. */
        APIKey: {
            id: string;
            name: string;
            prefix: string;
            role: components["schemas"]["Role"];
            created_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        /** @description Create-key input. role is member or admin only; an API key is never owner-equivalent (PRD-001 App A). */
        APIKeyInput: {
            name: string;
            role: components["schemas"]["Role"];
        };
        /** @description The created key plus its full secret. secret is returned exactly once in this response and never again; store it now. */
        APIKeyCreated: {
            key: components["schemas"]["APIKey"];
            secret: string;
        };
        /**
         * @description An org-level event type an outbound webhook can subscribe to (PRD-005 7.1).
         * @enum {string}
         */
        OutboundWebhookEvent: "monitor.down" | "monitor.recovery" | "incident.opened" | "incident.closed";
        /** @description Outbound webhook metadata. The signing secret is shown once at create/rotate and never stored in clear, so it is never present here. An empty events list means the webhook receives every event type. */
        OutboundWebhook: {
            id: string;
            url: string;
            enabled: boolean;
            events: components["schemas"]["OutboundWebhookEvent"][];
            created_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_delivery_at?: string | null;
            last_status?: string | null;
            last_error?: string | null;
        };
        /** @description Create/update input for an outbound webhook. url must be an absolute https URL. events may be empty (subscribe to all types). enabled defaults to true. */
        OutboundWebhookInput: {
            url: string;
            enabled?: boolean;
            events?: components["schemas"]["OutboundWebhookEvent"][];
        };
        /** @description The webhook plus its signing secret. secret is returned exactly once in this response (on create and on rotate) and never again; store it now to verify the X-Pulse-Signature header on deliveries. */
        OutboundWebhookCreated: {
            webhook: components["schemas"]["OutboundWebhook"];
            secret: string;
        };
        /** @enum {string} */
        InvitationState: "pending" | "accepted" | "revoked" | "expired";
        /** @description Pre-login preview of an invitation rendered on the accept page. inviter_name and org_name come from the token capability lookup (RFC-003 2.6). */
        InvitationPreview: {
            org_name: string;
            role: components["schemas"]["Role"];
            state: components["schemas"]["InvitationState"];
            email: string;
            inviter_name?: string | null;
        };
        Entitlements: {
            plan: components["schemas"]["Plan"];
            monitors_used: number;
            monitors_cap: number;
            seats_used: number;
            seats_cap: number;
            status_pages_used: number;
            status_pages_cap: number;
            min_interval_seconds: number;
            retention_days: number;
            regions_allowed: string[];
            regions_per_monitor_cap: number;
            custom_domain_allowed: boolean;
            api_write_allowed: boolean;
            failure_snapshot: boolean;
        };
        /** @description One tier in the public plan catalog (PRD-006 3): the plan id plus its limits. Reference config the FE renders as a comparison/upgrade table; carries no per-org usage. */
        PlanCatalogEntry: {
            plan: components["schemas"]["Plan"];
            monitors_cap: number;
            min_interval_seconds: number;
            seats_cap: number;
            status_pages_cap: number;
            retention_days: number;
            regions_allowed: string[];
            regions_per_monitor_cap: number;
            custom_domain_allowed: boolean;
            api_write_allowed: boolean;
            api_rate_per_min: number;
            channel_types: string[];
        };
        MonitorHeader: {
            key: string;
            value?: string;
            secret: boolean;
        };
        Monitor: {
            id: string;
            org_id: string;
            name: string;
            url: string;
            method: components["schemas"]["Method"];
            headers: components["schemas"]["MonitorHeader"][];
            body: string;
            expected_status_codes: string;
            timeout_seconds: number;
            interval_seconds: number;
            enabled: boolean;
            max_latency_ms: number | null;
            body_contains: string | null;
            failure_threshold: number;
            notification_channel_ids: string[];
            regions: string[];
            down_policy: components["schemas"]["DownPolicy"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MonitorListItem: {
            id: string;
            name: string;
            url: string;
            enabled: boolean;
            status: components["schemas"]["CoverageStatus"];
            /** Format: date-time */
            last_check_at: string | null;
            /** Format: date-time */
            next_check_at: string | null;
            interval_seconds: number;
            last_latency_ms: number | null;
            incident_open: boolean;
        };
        MonitorInput: {
            name: string;
            url: string;
            method: components["schemas"]["Method"];
            headers: components["schemas"]["MonitorHeader"][];
            body: string;
            expected_status_codes: string;
            timeout_seconds: number;
            interval_seconds: number;
            enabled: boolean;
            max_latency_ms: number | null;
            body_contains: string | null;
            failure_threshold: number;
            notification_channel_ids: string[];
            regions: string[];
            down_policy: components["schemas"]["DownPolicy"];
        };
        Channel: {
            id: string;
            org_id: string;
            name: string;
            type: components["schemas"]["ChannelType"];
            enabled: boolean;
            config: {
                [key: string]: unknown;
            };
        };
        ChannelInput: {
            name: string;
            type: components["schemas"]["ChannelType"];
            enabled: boolean;
            config: {
                [key: string]: unknown;
            };
        };
        /** @description Platform i18n shape (RFC-014). code is the stable key the frontend looks up; params are interpolation values; message is the English fallback. */
        LocalizedString: {
            code: string;
            params?: {
                [key: string]: unknown;
            };
            message: string;
        };
        CatalogField: {
            key: string;
            type: string;
            required: boolean;
            secret: boolean;
            enum?: string[];
            default?: string;
            label: components["schemas"]["LocalizedString"];
            help?: components["schemas"]["LocalizedString"];
        };
        ChannelTypeCatalogEntry: {
            type: components["schemas"]["ChannelType"];
            display_name: string;
            available: boolean;
            config_fields: components["schemas"]["CatalogField"][];
            required_plan?: components["schemas"]["Plan"];
            unavailable_reason?: components["schemas"]["LocalizedString"] | null;
        };
        ChannelTypeCatalog: {
            channel_types: components["schemas"]["ChannelTypeCatalogEntry"][];
        };
        RegionState: {
            region: string;
            /** @enum {string} */
            state: "scheduled" | "running" | "done" | "failed";
            healthy?: boolean | null;
            status_code?: number | null;
            latency_ms?: number | null;
            failure_reason?: components["schemas"]["FailureReason"] | null;
            /** Format: date-time */
            updated_at: string;
        };
        MonitorRegionStates: {
            /** @description monitor id -> its current per-region states */
            monitors: {
                [key: string]: components["schemas"]["RegionState"][];
            };
        };
        CheckNowAccepted: {
            monitor_id: string;
            regions: components["schemas"]["RegionState"][];
        };
        CheckResult: {
            id: string;
            monitor_id: string;
            region: string;
            /** Format: date-time */
            scheduled_at: string;
            /** Format: date-time */
            checked_at: string;
            healthy: boolean;
            failure_reason: components["schemas"]["FailureReason"] | null;
            status_code: number | null;
            latency_ms: number | null;
            error: string | null;
        };
        Incident: {
            id: string;
            monitor_id: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            cause_reason: components["schemas"]["FailureReason"];
            close_reason: components["schemas"]["CloseReason"] | null;
            duration_seconds: number | null;
        };
        FailureSnapshot: {
            monitor_id: string;
            /** Format: date-time */
            checked_at: string;
            status_code: number | null;
            headers: {
                [key: string]: string[];
            };
            body: string;
            truncated: boolean;
        };
        PageCheckResult: {
            items: components["schemas"]["CheckResult"][];
            next_cursor: string | null;
        };
        PageIncident: {
            items: components["schemas"]["Incident"][];
            next_cursor: string | null;
        };
        IncidentAnnotation: {
            id: string;
            incident_id: string;
            author_user_id: string;
            note: string;
            /** Format: date-time */
            created_at: string;
        };
        IncidentAnnotationInput: {
            note: string;
        };
        IncidentDetail: {
            id: string;
            monitor_id: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            cause_reason: components["schemas"]["FailureReason"];
            close_reason: components["schemas"]["CloseReason"] | null;
            duration_seconds: number | null;
            annotations: components["schemas"]["IncidentAnnotation"][];
        };
        /** @enum {string} */
        StatusPageState: "draft" | "published";
        /** @enum {string} */
        StatusPageTheme: "light" | "dark";
        /**
         * @description Reduced public status of a displayed monitor (PRD-004 3.2).
         * @enum {string}
         */
        PublicMonitorStatus: "operational" | "down";
        /**
         * @description Overall page banner derived from visible monitor statuses (PRD-004 4).
         * @enum {string}
         */
        PublicBanner: "operational" | "partial_outage" | "major_outage";
        /** @description A displayed-monitor entry in the editor (PRD-004 3.1). */
        StatusPageMonitorEntry: {
            monitor_id: string;
            display_name: string;
            order: number;
        };
        /** @description A status page as the authenticated editor sees it (PRD-004 2). */
        StatusPage: {
            id: string;
            org_id: string;
            name: string;
            slug: string;
            logo_url: string;
            accent_color: string;
            theme: components["schemas"]["StatusPageTheme"];
            state: components["schemas"]["StatusPageState"];
            custom_domain: string | null;
            display_monitors: components["schemas"]["StatusPageMonitorEntry"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Create/update a status page. display_monitors replaces the displayed-monitor list. custom_domain is owner/admin only and unused in v1 (PRD-004 9.1). */
        StatusPageInput: {
            name: string;
            slug: string;
            logo_url: string;
            accent_color: string;
            theme: components["schemas"]["StatusPageTheme"];
            custom_domain?: string | null;
            display_monitors: components["schemas"]["StatusPageMonitorEntry"][];
        };
        StatusPagePublish: {
            published: boolean;
        };
        /** @description Uptime over the public windows (PRD-004 3.3); has_* false = no data. */
        PublicUptime: {
            uptime_24h: number;
            uptime_7d: number;
            uptime_90d: number;
            has_24h: boolean;
            has_7d: boolean;
            has_90d: boolean;
        };
        /** @description One cell of the recent history bar (up/down per period, PRD-004 3.4). */
        PublicHistoryPoint: {
            /** Format: date-time */
            at: string;
            up: boolean;
        };
        /** @description Public-safe projection of one displayed monitor (PRD-004 3.6 left column). Carries ONLY the friendly name, public status, uptime, and history; it never carries the raw url, method, headers, body, assertions, or failure detail. */
        PublicDisplayedMonitor: {
            display_name: string;
            status: components["schemas"]["PublicMonitorStatus"];
            uptime: components["schemas"]["PublicUptime"];
            history: components["schemas"]["PublicHistoryPoint"][];
        };
        /** @description A public incident entry by friendly name only (PRD-004 5.1). */
        PublicIncident: {
            display_name: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            duration_seconds: number | null;
            resolved: boolean;
        };
        /** @description The public-safe page projection served unauthenticated (PRD-004 3.6). Only branding, the banner, the visible displayed monitors, and recent public incidents. No internal monitor detail is present. */
        PublicStatusPage: {
            name: string;
            slug: string;
            logo_url: string;
            accent_color: string;
            theme: components["schemas"]["StatusPageTheme"];
            banner: components["schemas"]["PublicBanner"];
            monitors: components["schemas"]["PublicDisplayedMonitor"][];
            incidents: components["schemas"]["PublicIncident"][];
            uptime_max_window: string;
        };
    };
    responses: {
        /** @description not signed in */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description rate limited; retry after the indicated delay */
        TooManyRequests: {
            headers: {
                /** @description seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description validation failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OrgId: string;
        Id: string;
        UserId: string;
        Token: string;
        Provider: components["schemas"]["IdentityProviderName"];
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdate"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listMyIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    unlinkMyIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembership"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembership"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembership"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    leaveOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    changeMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleUpdate"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    transferOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnership"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description no seat available on the plan (upsell) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    revokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getInvitationPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreview"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembership"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIKeyInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyCreated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    revokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundWebhook"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundWebhookInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundWebhookCreated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundWebhook"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundWebhookInput"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundWebhook"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    rotateWebhookSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundWebhookCreated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entitlements"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanCatalogEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMonitors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorListItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description monitor cap reached on the plan (upsell) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorInput"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description the update would exceed a plan limit (upsell) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    checkNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description accepted; the check was enqueued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckNowAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getMonitorRegionStates: {
        parameters: {
            query?: {
                monitor_id?: string;
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorRegionStates"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listResults: {
        parameters: {
            query?: {
                range?: components["schemas"]["ResultsRange"];
                region?: string;
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageCheckResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listMonitorIncidents: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageIncident"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getLastFailure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description no failure has been captured for this monitor */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChannelTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelTypeCatalog"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelInput"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    testChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listIncidents: {
        parameters: {
            query?: {
                status?: "open" | "all";
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageIncident"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    addIncidentAnnotation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentAnnotationInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentAnnotation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    closeIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listStatusPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPage"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createStatusPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPageInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description status-page cap reached on the plan (upsell, PRD-004 2.3) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getStatusPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateStatusPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPageInput"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteStatusPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    publishStatusPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPagePublish"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getPublicStatusPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatusPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
